// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFo2QJUK1WR-yVd-u6HNmPqO66Joor3so',
    appId: '1:45334650594:web:2f848e26e8f9eedc7548bb',
    messagingSenderId: '45334650594',
    projectId: 'chatapp-ea385',
    authDomain: 'chatapp-ea385.firebaseapp.com',
    storageBucket: 'chatapp-ea385.firebasestorage.app',
    measurementId: 'G-WS5D4DC8ZL',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdj32lWJIPm8PZkLcytZVIZB2-dCUkQJM',
    appId: '1:45334650594:android:d2290c67e51548847548bb',
    messagingSenderId: '45334650594',
    projectId: 'chatapp-ea385',
    storageBucket: 'chatapp-ea385.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUz9gAadh7UxDmSajdCO4GHWb0oF5wnw0',
    appId: '1:45334650594:ios:9f548f9a6a647a187548bb',
    messagingSenderId: '45334650594',
    projectId: 'chatapp-ea385',
    storageBucket: 'chatapp-ea385.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUz9gAadh7UxDmSajdCO4GHWb0oF5wnw0',
    appId: '1:45334650594:ios:9f548f9a6a647a187548bb',
    messagingSenderId: '45334650594',
    projectId: 'chatapp-ea385',
    storageBucket: 'chatapp-ea385.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}